<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://perfectmatcher.webapp.johnyjay.com" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://perfectmatcher.webapp.johnyjay.com" xmlns:intf="http://perfectmatcher.webapp.johnyjay.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://perfectmatcher.webapp.johnyjay.com" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="perfectmatcher">
    <complexType/>
   </element>
   <element name="perfectmatcherResponse">
    <complexType>
     <sequence>
      <element name="perfectmatcherReturn" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="perfectmatcherResponse">

      <wsdl:part element="impl:perfectmatcherResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="perfectmatcherRequest">

      <wsdl:part element="impl:perfectmatcher" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="PerfectMatcher">

      <wsdl:operation name="perfectmatcher">

         <wsdl:input message="impl:perfectmatcherRequest" name="perfectmatcherRequest">

       </wsdl:input>

         <wsdl:output message="impl:perfectmatcherResponse" name="perfectmatcherResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="PerfectMatcherSoapBinding" type="impl:PerfectMatcher">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="perfectmatcher">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="perfectmatcherRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="perfectmatcherResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="PerfectMatcherService">

      <wsdl:port binding="impl:PerfectMatcherSoapBinding" name="PerfectMatcher">

         <wsdlsoap:address location="http://localhost:8080/webapp/services/PerfectMatcher"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
